export type KanbanDirectionId = "sales" | "fulfillment" | "warranty";

export type KanbanFlag =
  | "overdue"
  | "viewed"
  | "deadline_changed"
  | "fields_filled"
  | "urgent";

export interface KanbanColumn {
  id: string;
  title: string;
  accent: string;
}

export interface KanbanDeal {
  id: string;
  number: string;
  direction: KanbanDirectionId;
  columnId: string;
  client: string;
  amount: number;
  owner: string;
  ownerInitials: string;
  workType: string;
  quantity: number;
  deadline: string;
  manufacturer: string;
  note: string;
  flags: KanbanFlag[];
}

export const KANBAN_DIRECTIONS: {
  id: KanbanDirectionId;
  label: string;
  short: string;
}[] = [
  { id: "sales", label: "Продажа", short: "Продажа" },
  {
    id: "fulfillment",
    label: "Поставка / Доставка / Монтаж",
    short: "Поставка",
  },
  {
    id: "warranty",
    label: "Пост гарантийный сервис",
    short: "Сервис",
  },
];

export const KANBAN_COLUMNS: Record<KanbanDirectionId, KanbanColumn[]> = {
  sales: [
    { id: "new", title: "Новая заявка", accent: "#7a8f84" },
    { id: "measure", title: "Замер", accent: "#2f6fed" },
    { id: "quote", title: "КП", accent: "#9a7b4f" },
    { id: "talk", title: "Переговоры", accent: "#b86a3d" },
    { id: "deposit", title: "Предоплата", accent: "#0b6b56" },
    { id: "won", title: "В производство", accent: "#1f7a4d" },
  ],
  fulfillment: [
    { id: "not_sent", title: "Не отправленные в работу", accent: "#c45c4a" },
    { id: "ksenia", title: "В обработке у Ксении", accent: "#c4a035" },
    { id: "supplier", title: "Заявка у поставщика", accent: "#d4a017" },
    { id: "rek_katya", title: "Рек в обработке у Кати", accent: "#2aa3a0" },
    { id: "rek_supplier", title: "Рекламация у поставщика", accent: "#c45c4a" },
    { id: "manager_fix", title: "Требует доработки менеджера", accent: "#b8a04a" },
    { id: "in_work", title: "Заказ в работе", accent: "#0b6b56" },
    { id: "rek_work", title: "Рекламация в работе", accent: "#3d8b5a" },
  ],
  warranty: [
    { id: "intake", title: "Новое обращение", accent: "#7a8f84" },
    { id: "diag", title: "Диагностика", accent: "#2f6fed" },
    { id: "agree", title: "Согласование", accent: "#9a7b4f" },
    { id: "service_work", title: "В работе", accent: "#0b6b56" },
    { id: "parts", title: "Ожидает запчасть", accent: "#b86a3d" },
    { id: "closed", title: "Закрыто", accent: "#1f7a4d" },
  ],
};

export const FLAG_LABELS: Record<KanbanFlag, string> = {
  overdue: "Просрочена",
  viewed: "Просмотрена",
  deadline_changed: "Изменён крайний срок",
  fields_filled: "Поля заполнены",
  urgent: "Срочно",
};

export const kanbanDeals: KanbanDeal[] = [
  {
    id: "kd1",
    number: "546-2026",
    direction: "fulfillment",
    columnId: "not_sent",
    client: "Семья Ковалёвых",
    amount: 565430,
    owner: "Илья Морозов",
    ownerInitials: "ИМ",
    workType: "Установка дверей",
    quantity: 7,
    deadline: "30.06.2026",
    manufacturer: "Atelier",
    note: "Пишем общее количество дверей и комплектацию по проёмам.",
    flags: ["overdue"],
  },
  {
    id: "kd2",
    number: "512-2026",
    direction: "fulfillment",
    columnId: "not_sent",
    client: "Артём Белов",
    amount: 132000,
    owner: "Анна Крылова",
    ownerInitials: "АК",
    workType: "Доставка + монтаж",
    quantity: 2,
    deadline: "18.09.2026",
    manufacturer: "Noir",
    note: "Эмаль Graphite, скрытый короб.",
    flags: ["viewed"],
  },
  {
    id: "kd3",
    number: "498-2026",
    direction: "fulfillment",
    columnId: "supplier",
    client: "ООО «Север Девелопмент»",
    amount: 812000,
    owner: "Мария Соколова",
    ownerInitials: "МС",
    workType: "Поставка Invisible",
    quantity: 18,
    deadline: "12.10.2026",
    manufacturer: "Invisible Pro",
    note: "Офис на Павелецкой, высота 2400.",
    flags: ["fields_filled"],
  },
  {
    id: "kd4",
    number: "501-2026",
    direction: "fulfillment",
    columnId: "supplier",
    client: "Студия «Форма»",
    amount: 521070,
    owner: "Илья Морозов",
    ownerInitials: "ИМ",
    workType: "Поставка Atelier",
    quantity: 6,
    deadline: "05.10.2026",
    manufacturer: "Atelier",
    note: "Шоурум клиента, ночной доступ.",
    flags: ["deadline_changed"],
  },
  {
    id: "kd5",
    number: "477-2026",
    direction: "fulfillment",
    columnId: "rek_supplier",
    client: "Елена Орлова",
    amount: 198400,
    owner: "Анна Крылова",
    ownerInitials: "АК",
    workType: "Рекламация фурнитуры",
    quantity: 1,
    deadline: "20.09.2026",
    manufacturer: "Crystal",
    note: "Магнитный замок — люфт после монтажа.",
    flags: ["urgent", "overdue"],
  },
  {
    id: "kd6",
    number: "460-2026",
    direction: "fulfillment",
    columnId: "manager_fix",
    client: "Игорь Савельев",
    amount: 106560,
    owner: "Павел Орлов",
    ownerInitials: "ПО",
    workType: "Уточнение комплектации",
    quantity: 4,
    deadline: "22.09.2026",
    manufacturer: "Natura",
    note: "Нужны доборы под кирпич 380 мм.",
    flags: ["viewed"],
  },
  {
    id: "kd7",
    number: "440-2026",
    direction: "fulfillment",
    columnId: "in_work",
    client: "ЖК «Резиденции Парк»",
    amount: 2480000,
    owner: "Илья Морозов",
    ownerInitials: "ИМ",
    workType: "Монтаж партии",
    quantity: 24,
    deadline: "28.09.2026",
    manufacturer: "Atelier",
    note: "Корпус 3, слот бригады «Север».",
    flags: ["fields_filled"],
  },
  {
    id: "kd8",
    number: "441-2026",
    direction: "fulfillment",
    columnId: "in_work",
    client: "Таунхаус, Рублёвка",
    amount: 3150958,
    owner: "Анна Крылова",
    ownerInitials: "АК",
    workType: "Монтаж Noir",
    quantity: 9,
    deadline: "28.09.2026",
    manufacturer: "Noir",
    note: "Защитная плёнка до чистовой.",
    flags: ["viewed"],
  },
  {
    id: "kd9",
    number: "420-2026",
    direction: "fulfillment",
    columnId: "rek_work",
    client: "Семья Ковалёвых",
    amount: 486404,
    owner: "Сервис",
    ownerInitials: "СР",
    workType: "Гарантийный выезд",
    quantity: 1,
    deadline: "05.10.2026",
    manufacturer: "Atelier",
    note: "Подтяжка доводчика на кухне.",
    flags: ["deadline_changed"],
  },
  {
    id: "kd10",
    number: "419-2026",
    direction: "fulfillment",
    columnId: "rek_work",
    client: "ООО «Север Девелопмент»",
    amount: 500000,
    owner: "Сервис",
    ownerInitials: "СР",
    workType: "Перезамер + довоз",
    quantity: 3,
    deadline: "15.10.2026",
    manufacturer: "Invisible Pro",
    note: "После сдвига перегородок архитектором.",
    flags: ["urgent"],
  },

  // sales
  {
    id: "ks1",
    number: "610-2026",
    direction: "sales",
    columnId: "new",
    client: "Дизайн-бюро «Линия»",
    amount: 0,
    owner: "Анна Крылова",
    ownerInitials: "АК",
    workType: "Консультация в салоне",
    quantity: 5,
    deadline: "16.09.2026",
    manufacturer: "—",
    note: "Интерес к Invisible и Crystal.",
    flags: ["viewed"],
  },
  {
    id: "ks2",
    number: "608-2026",
    direction: "sales",
    columnId: "measure",
    client: "Елена Орлова",
    amount: 0,
    owner: "Илья Морозов",
    ownerInitials: "ИМ",
    workType: "Замер проёмов",
    quantity: 5,
    deadline: "13.09.2026",
    manufacturer: "—",
    note: "Хамовники, скрытые короба.",
    flags: ["fields_filled"],
  },
  {
    id: "ks3",
    number: "590-2026",
    direction: "sales",
    columnId: "quote",
    client: "ООО «Север Девелопмент»",
    amount: 1540000,
    owner: "Мария Соколова",
    ownerInitials: "МС",
    workType: "КП офис",
    quantity: 18,
    deadline: "20.09.2026",
    manufacturer: "Invisible Pro",
    note: "PDF КП после подтверждения высоты.",
    flags: ["deadline_changed"],
  },
  {
    id: "ks4",
    number: "585-2026",
    direction: "sales",
    columnId: "talk",
    client: "Артём Белов",
    amount: 812000,
    owner: "Анна Крылова",
    ownerInitials: "АК",
    workType: "Переговоры по эмали",
    quantity: 9,
    deadline: "18.09.2026",
    manufacturer: "Noir",
    note: "Сравнивают Noir и Atelier White Silk.",
    flags: ["urgent"],
  },
  {
    id: "ks5",
    number: "570-2026",
    direction: "sales",
    columnId: "deposit",
    client: "Игорь Савельев",
    amount: 392000,
    owner: "Анна Крылова",
    ownerInitials: "АК",
    workType: "Предоплата 30%",
    quantity: 4,
    deadline: "25.09.2026",
    manufacturer: "Natura",
    note: "Ждём поступление на расчётный.",
    flags: ["fields_filled"],
  },
  {
    id: "ks6",
    number: "555-2026",
    direction: "sales",
    columnId: "won",
    client: "Студия «Форма»",
    amount: 268000,
    owner: "Павел Орлов",
    ownerInitials: "ПО",
    workType: "Передано в поставку",
    quantity: 3,
    deadline: "12.09.2026",
    manufacturer: "Atelier",
    note: "Оплачено полностью.",
    flags: ["viewed"],
  },

  // warranty
  {
    id: "kw1",
    number: "S-102",
    direction: "warranty",
    columnId: "intake",
    client: "Семья Ковалёвых",
    amount: 0,
    owner: "Сервис",
    ownerInitials: "СР",
    workType: "Гарантия · доводчик",
    quantity: 1,
    deadline: "05.10.2026",
    manufacturer: "Atelier",
    note: "Заявка через WhatsApp.",
    flags: ["viewed"],
  },
  {
    id: "kw2",
    number: "S-098",
    direction: "warranty",
    columnId: "diag",
    client: "Елена Орлова",
    amount: 0,
    owner: "Андрей К.",
    ownerInitials: "АК",
    workType: "Диагностика замка",
    quantity: 1,
    deadline: "18.09.2026",
    manufacturer: "Crystal",
    note: "Фото от клиента получены.",
    flags: ["fields_filled"],
  },
  {
    id: "kw3",
    number: "S-090",
    direction: "warranty",
    columnId: "agree",
    client: "Игорь Савельев",
    amount: 12400,
    owner: "Анна Крылова",
    ownerInitials: "АК",
    workType: "Согласование замены",
    quantity: 1,
    deadline: "22.09.2026",
    manufacturer: "Natura",
    note: "Вне гарантии — коммерческое предложение.",
    flags: ["deadline_changed"],
  },
  {
    id: "kw4",
    number: "S-084",
    direction: "warranty",
    columnId: "service_work",
    client: "Студия «Форма»",
    amount: 0,
    owner: "Бригада «Центр»",
    ownerInitials: "БЦ",
    workType: "Регулировка петель",
    quantity: 2,
    deadline: "17.09.2026",
    manufacturer: "Atelier",
    note: "Выезд согласован на 11:00.",
    flags: ["urgent"],
  },
  {
    id: "kw5",
    number: "S-070",
    direction: "warranty",
    columnId: "parts",
    client: "ООО «Север Девелопмент»",
    amount: 0,
    owner: "Сервис",
    ownerInitials: "СР",
    workType: "Ожидание скрытого короба",
    quantity: 2,
    deadline: "30.09.2026",
    manufacturer: "Invisible Pro",
    note: "Поставщик подтвердил отгрузку.",
    flags: ["overdue"],
  },
  {
    id: "kw6",
    number: "S-055",
    direction: "warranty",
    columnId: "closed",
    client: "Артём Белов",
    amount: 0,
    owner: "Сервис",
    ownerInitials: "СР",
    workType: "Акт выполненных работ",
    quantity: 1,
    deadline: "01.09.2026",
    manufacturer: "Noir",
    note: "Закрыто без замечаний.",
    flags: ["fields_filled"],
  },
];

export function formatKanbanMoney(value: number): string {
  if (!value) return "—";
  return new Intl.NumberFormat("ru-RU", {
    style: "currency",
    currency: "RUB",
    maximumFractionDigits: 0,
  }).format(value);
}
